### ISSUE TITLE
Python Face Recognition using OpenCV on Buildroot

### ISSUE THREAD

**Issue by shashankchandrasekaran** [shashankchandrasekaran/final-project-assignment-shashankchandrasekaran#7]
Setup the face recognition algorithm in buildroot using https://github.com/cu-ecen-aeld/buildroot-assignments-base/wiki/Facial-Recognition-Application-using-OpenCV-3-on-Buildroot as reference

DoD:

- [x] Download the packages required for face recognition in buildroot
- [x] Modify any files in repository as per our application or missing information in wiki page
- [x] Test the sample program on Raspberry Pi

Blockers: Missing XML module is not allowing to import Face_Recognition_models package and throwing an exception.

**Comment by harshberiwal** [comment]
1. Able to install all the face Recognition packages in the target and located at /usr/bin/python-3.8/site-packages/ 


![Image](https://user-images.githubusercontent.com/111919475/233903697-14cee145-322f-41b2-bcdf-22525853b1b5.png)

2. Added the application file to compare images using the link https://github.com/cu-ecen-aeld/buildroot-assignments-base/wiki/Facial-Recognition-Application-using-OpenCV-3-on-Buildroot

3.  When tried running face_recog.py to compare faces through Camera, getting an error while importing face_recognition_models. 


![Image](https://user-images.githubusercontent.com/111919475/233904231-9809872a-9f3e-4168-9670-ecf37e01ccc5.png)

This is due to missing XML Module 


![Image](https://user-images.githubusercontent.com/111919475/233904626-5da1dcee-40b3-4d82-9a28-c4d71ce9ed62.png)


The commit is [here](https://github.com/cu-ecen-aeld/final-project-shashankchandrasekaran/commit/7e776691c45a0ac6c30d6fe30a7efbcd56648a2f)

**Comment by harshberiwal** [comment]
Make Python-reconfigure fixed it. Was also getting a cv2 error  which was fixed after adding Python in OpenCV3 and doing a fresh rebuild. The commit is [here ](https://github.com/cu-ecen-aeld/final-project-shashankchandrasekaran/commit/39d69b03bdc73e32dc0ad4f79fb4fa2d823c5008)


![Image](https://user-images.githubusercontent.com/111919475/235382043-7e6c0f8a-1726-4739-be7e-0d8980e0d939.jpg)
